# Generated by Django 3.2.16 on 2022-12-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20221231_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='date_of_travel',
            field=models.CharField(default='20220101', max_length=10),
        ),
    ]
